#!/usr/bin/env python
# Generated by jaraco.develop (https://bitbucket.org/jaraco/jaraco.develop)
from setuptools import find_packages
setup_params = dict(
	name='jaraco.modb',
	description="MongoDB Object DataBase (MODB) for Python objects",
	use_hg_version=dict(increment='0.1'),
	packages=find_packages(),
	namespace_packages=['jaraco'],
	zip_safe=False,
	install_requires=[
		'jsonpickle',
		'pymongo',
	],
	setup_requires=[
		'hgtools',
	],
)
if __name__ == '__main__':
	from setuptools import setup
	setup(**setup_params)
